config/routes.rb
VrnElectro::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root to: 'main#index'

  resources :categories, only: [:show] do
    resources :products, only: [:show]
  end

  namespace :cart do
    post 'items/:id', to: "items#create", as: 'items'
  end

  get 'cart' => 'cart#index', as: 'cart_index'
  patch 'cart' => 'cart#update', as: 'cart'

  resources :orders, only: [:new, :create]

end

app/models/cart.rb
class Cart

  attr_reader :items

  def initialize
    @items = []
  end

  def add(product_id, quantity=1)
    current_item = self.item(product_id)
    if current_item
      current_item.increment_quantity(quantity)
    else
      @items << Cart::Item.new(product_id, quantity)
    end
  end

  def price
    @items.sum{ |item| item.price }
  end

  def quantity
    @items.sum{ |item| item.quantity }
  end

  def empty?
    @items.size <= 0
  end

  def empty!
    @items.delete_if { |i| true }
  end

  def delete_item(id)
    @items.delete_if { |item| item.product_id == id.to_i }
  end

  def delete_broken_items
    @items.delete_if { |i| ! !!Product.find(i.product_id) }
  end

  def item(id)
    @items.find { |item| item.product.id == id }
  end

  def to_s
    datas = []
    items.each { |item| datas << item.to_s }
    datas << "Итого: #{price} руб."
    datas
  end

end

app/models/cart/item.rb
class Cart::Item

  attr_reader :product_id
  attr_accessor :quantity

  def initialize(product_id, quantity=1)
    @product_id = product_id
    @quantity = quantity.to_i
  end

  def product
    begin
      Product.find(self.product_id)
    rescue ActiveRecord::RecordNotFound
      Product.new(name: 'Error! This item not found.')
    end
  end

  def increment_quantity(quantity)
    @quantity += quantity
  end

  def name
    product.name
  end

  def price
    product.price * @quantity.to_i
  end

  def to_s
    "#{product.name}, #{quantity} шт. , #{price} руб."
  end

end

app/controllers/cart/items_controller.rb
class Cart::ItemsController < ApplicationController

  def create
    @cart.add(Product.find(params[:id]).id)
  end  

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def index
    if @cart.empty?
      gflash warning: t('cart.empty')
      redirect_to root_path
    end
  end

  def update
    params[:cart_items].each do |item, quantity|
      current_item = @cart.item(item.to_i)
      @cart.items.delete(current_item) if quantity.to_i == 0
      current_item.quantity = quantity.to_i if current_item
    end
    gflash notice: t('cart.updated')
    redirect_to cart_index_path
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.haml
%h1= t('cart.title')
= form_for :cart_item, url: cart_path, method: :patch do |f|
  %table#cart_table.table.table-hover.table-bordered.table-condensed
    %thead
      %th.name= t('cart_item.name')
      %th.quantity= t('cart_item.quantity_short')
      %th.price= t('cart_item.price')
    %tbody
      - @cart.items.each do |item|
        = render partial: 'cart/items/item', locals: { item: item, f: f }
    %tfoot
      %tr.sum
        %td{ colspan: 2 }= t('cart.sum')
        %td= @cart.price.round(2)
  .form-actions
    = f.submit t('cart.recalculate'), class: 'btn btn-success'
    = link_to t('cart.checkout'), new_order_path, class: 'btn btn-primary'