config/routes.rb
VrnElectro::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root to: 'main#index'

  resources :categories, only: [:show] do
    resources :products, only: [:show]
  end

  namespace :cart do
    post 'items/:id', to: "items#create", as: 'items'
  end

  get 'cart' => 'cart#index', as: 'cart_index'
  patch 'cart' => 'cart#update', as: 'cart'

  resources :orders, only: [:new, :create]

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_reader :name
  #attr_accessible :additional, :address, :first_name, :last_name, :phone, :email
  validates :first_name, :last_name, :phone, :address, presence: true

  has_many :items, dependent: :destroy

  state_machine :state, initial: :initialized do
    
    state :initialized, :inprogress, :finished

    event :finish do
      transition all => :finished
    end

  end

  def name
    self.class.model_name.human + " #" + id.to_s
  end

end

app/models/order/item.rb
class Order::Item < ActiveRecord::Base
  #attr_accessible :order_id, :price, :product_id, :quantity
  validates :order_id, :price, :product_id, :quantity, presence:true

  def price
    read_attribute(:price).to_f
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new; end

  def create
    begin
      ActiveRecord::Base.transaction do
        @order = Order.new(params[:order])
        @order.save!
       create_order_items!
        OrderMailer.order(get_order_datas(params[:order]), @cart.to_s).deliver
        @cart.empty!
      end
      gflash success: t('order.save.success')
      redirect_to root_path
     rescue
       gflash error: t('order.save.error')
       render :new
     end
   end

   private
    
    def create_order_items!
      @cart.items.each do |item|
        Order::Item.create!(product_id: item.product_id,
                            quantity: item.quantity,
                            price: item.price,
                            order_id: @order.id)
      end
    end
  
    def get_order_datas(params)
      datas = {}
      params.each do |k, v|
        datas[t(".orders.new.#{k}")] = v
      end
      datas
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/new.html.haml
%h1 Оформление заказа
= error_messages(@order)
= form_for :order, url: orders_path, method: :post, html: { id: 'new_order' } do |f|
  .control-group
    = f.label :first_name, t('.first_name'), class: 'control-label'
    .controls
      = f.text_field :first_name
  .control-group
    = f.label :last_name, t('.last_name'), class: 'control-label'
    .controls
      = f.text_field :last_name
  .control-group
    = f.label :phone, t('.phone'), class: 'control-label'
    .controls
      = f.text_field :phone
  .control-group
    = f.label :email, t('.email'), class: 'control-label'
    .controls
      = f.email_field :email
  .control-group
    = f.label :address, t('.address'), class: 'control-label'
    .controls
      = f.text_area :address
  .control-group
    = f.label :additional, t('.additional'), class: 'control-label'
    .controls
      = f.text_area :additional
  .form-actions
    = f.submit t('order.create'), class: 'btn btn-primary btn-large'