config/routes.rb
VrnElectro::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root to: 'main#index'

  resources :categories, only: [:show] do
    resources :products, only: [:show]
  end

  namespace :cart do
    post 'items/:id', to: "items#create", as: 'items'
  end

  get 'cart' => 'cart#index', as: 'cart_index'
  patch 'cart' => 'cart#update', as: 'cart'

  resources :orders, only: [:new, :create]

end

app/models/product.rb
class Product < ActiveRecord::Base
  #attr_accessible :description, :lot, :name, :price, :related_products, :category_id, :photos_attributes, :remove_image, :disabled, :mark
  validates :name, :price, presence: true
  validates :lot, uniqueness: true, allow_blank: true
  has_ancestry
  extend FriendlyId
  friendly_id :name, use: [:history, :finders]
  serialize :related_products, Array
  has_many :photos, dependent: :destroy
  belongs_to :category
  accepts_nested_attributes_for :photos, allow_destroy: true
  has_paper_trail
  
  default_scope -> { where(disabled: false).order('category_id, price, name') }
  scope :iek, -> { where(mark: 'iek') }
  scope :fluke, -> { where(mark: 'fluke') }
  scope :main, -> { where(show_on_main: true) }
  
  def category_id_enum
    Category.new.parent_id_enum 
  end
  
  def related_products_enum
    Product.order(:name).map { |p| [p.name, p.id] }
  end

  def disabled?
    disabled
  end

  def related
    self[:related_products][1..-1] ? self.class.includes(:category).find(self[:related_products][1..-1]) : []
  end

  def has_related?
    related.size > 0
  end

  def photos_count
    photos.count
  end

  def main_photo
    photos.first.try(:image) || false
  end

  def photos?
    photos.size > 0
  end

  def more_photos?
    photos.size > 1
  end

  def more_photos
    photos[1..-1]
  end

  def destroy
    update_attributes(disabled: true)
  end
  alias destroy! destroy

  def super_destroy!
    self.class.superclass.instance_method(:destroy).bind(self).call
  end

  class << self
    def super_destroy_all!
      self.unscoped.all.each { |p| p.super_destroy! }
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  authorize_resource

  def show
    @product = Product.includes(:category, :photos).find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_list.html.haml
%ul#products
  - products.try(:each) do |product|
    %li= render partial: 'products/product', locals: { product: product }

app/views/products/_product.html.haml
.img= image_tag product.main_photo.small if product.photos?
.name= link_to truncate(product.name, length: 64, sperator: ' ', omission: '...'), category_product_path(product.category, product)
.price
  = product.price
  руб.
= link_to cart_items_path(product), class: 'btn btn-info btn-mini btn-buy', remote: true, method: :post do
  %i.icon-shopping-cart.icon-white
  = t('actions.to_cart')

app/views/products/_related_product.html.haml
.img= image_tag product.main_photo.thumb if product.photos?
.name= link_to truncate(product.name, length: 24, sperator: ' ', omission: '...'), category_product_path(product.category, product)

app/views/products/show.html.haml
%ul.breadcrumb
  %li
    = link_to @product.category.name, category_path(@product.category)
    %span.divider /
  %li.active= @product.name
%h1= @product.name
- @product.photos.try(:each) do |photo|
  = link_to image_tag(photo.image.small, class: 'photo'), photo.image.medium.url, class: 'fancybox', rel: "product-#{@product.id}"
- if !@product.lot.empty?
  %p
    Лот:
    = @product.lot
%p
  Цена:
  = @product.price
  руб.
= link_to(cart_items_path(@product), class: 'btn btn-success', remote: true, method: :post) do
  %i.icon-shopping-cart.icon-white
  = t('actions.to_cart')
%p!= @product.description if !@product.description.empty?
%ul#products
- if @product.has_related?
  #related_products
    %h4 Рекоммендуем:
    %ul
      - @product.related.try(:each) do |product|
        %li.thumbnail
          = render partial: 'products/related_product', locals: { product: product }